make:
	g++ --std=c++11 -march=native val_test01_solved.cpp -o val_test01_solved
	g++ --std=c++11 -march=native val_test02_solved.cpp -o val_test02_solved
	gcc -march=native -fopenmp omp_solved2.c -o omp_solved2
	gcc -march=native -fopenmp omp_solved3.c -o omp_solved3
	gcc -march=native -fopenmp omp_solved4.c -o omp_solved4
	gcc -march=native -fopenmp omp_solved5.c -o omp_solved5
	gcc -march=native -fopenmp omp_solved6.c -o omp_solved6
	g++ -O3 -fopenmp --std=c++11 -march=native jacobi2D-omp.cpp -o jacobi2D-omp
	g++ -O3 -fopenmp --std=c++11 -march=native gs2D-omp.cpp -o gs2D-omp